### ISSUE TITLE
🚨 Figure out a better return type for the rateLimitHandler function

### ISSUE THREAD

**Issue by GV14982** [GV14982/async-airtable#32]
Currently the `asyncAirtable#rateLimitHandler` method currently has a return type of `Promise<any>`, which is not ideal and causing a linter warning.

We need to come up with a better return type to handle this.

**Comment by MoralCode** [comment]
this seems like it stems from the `resolve(data)` line. maybe `Promise<object>` would be slightly more specific if the promise resolves with the value of the JSON from the request. might also need to make a custom type thats `object | Error` to make sure it covers the error case.

Alternatively, maybe use [generics](https://www.typescriptlang.org/docs/handbook/2/generics.html) and have the caller specify what type it is expecting since it is the one making the request and probably knows what the format of the data is expected to be

**Comment by GV14982** [comment]
Addressed with #77
