### ISSUE TITLE
ReferenceError: define is not defined

### ISSUE THREAD

**Issue by stevenpersia** [GV14982/async-airtable#38]
**Describe the bug**
After install and import, I've got this error. I've tried on multiple node version.

**To Reproduce**
Here a link to runkit : https://runkit.com/stevenpersia/referenceerror-define-is-not-defined

**Expected behavior**
Except to try your amazing tool :smiley: 

**Screenshots**
![image](https://user-images.githubusercontent.com/24541365/102016793-0206f880-3d63-11eb-8792-103e08b1585b.png)

**Comment by GV14982** [comment]
Hi Steven, thanks for submitting this issue.

This is actually an issue with how we are compiling the the package currently. This is will be fixed in the next release. For now, if you just want to try using asyncairtable@next (which is the release from the develop branch) and let me know if that helps.

**Comment by avanavana** [comment]
I am having the same issue.  Figured it was because it needs to be loaded with `amd-loader`, so I added that, but then I received this error:

![Screen Shot 2020-12-14 at 4 20 48 PM](https://user-images.githubusercontent.com/5025683/102137244-840d2500-3e28-11eb-96bd-ed54becfa7bd.png)

Shame, because I really would love to use this module instead of the regular Airtable API.

I also tried using [this guy's define shim](https://gist.github.com/kriszyp/650000) for nodejs, and I got an error: "buildOpts is not defined".

**Comment by GV14982** [comment]
Hi @avanavana, thanks for reporting the issue. I'll see if I can get a release setup tonight, as it seems that runkit does not let you use tags when downloading packages.

**Comment by stevenpersia** [comment]
I've got same issue as above when I use asyncairtable@next on local node project : `AsyncAirtable is not a constructor`.

**Comment by avanavana** [comment]
> Hi @avanavana, thanks for reporting the issue. I'll see if I can get a release setup tonight, as it seems that runkit does not let you use tags when downloading packages.

Thanks, I'm in no rush, but I am glad you are working on this because when it's ready I will be so glad to switch over to async and clean my code up.

This wasn't just runkit- on my local node project I tried asyncairtable@next (the second to last screenshot) too.

**Comment by GV14982** [comment]
Can you test asyncairtable@next on a local node environment just to be sure it works? If it does I'll do a regular release so it can be used correctly on tools like runkit.

**Comment by stevenpersia** [comment]
It works great on my side ! Thank you for your reactivity :tada: :+1:

**Comment by GV14982** [comment]
Perfect! I will get a release together for tonight. Please let me know any thoughts you have and if this is missing any features you might want/need!

**Comment by avanavana** [comment]
> Can you test asyncairtable@next on a local node environment just to be sure it works? If it does I'll do a regular release so it can be used correctly on tools like runkit.

Sorry, haven't had time to look at this until now.  Works like a charm.  Thanks so much for this!

**Comment by GV14982** [comment]
Just an FYI, I just released 1.2.4 so now it is available on both RunKit and via CDN's such as UNPKG and jsDelivr 🙂
